config/routes.rb
Homeapp::Application.routes.draw do
  root to: "root#index"
  resources :root, :only => [:index]
  resources :resume, :only => [:index]
  resources :asteroids
  resources :snakes
  match "contact", :to => "pages#contact", :as => "contact", :via => :get
  match "send_email", :to => "pages#send_email", :as => "send_email", :via => :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/asteroids_controller.rb
class AsteroidsController < ApplicationController

	def show
	end

	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def contact
	end

	def send_email
		sender_info = params[:sender_info]
		if ContactMailer.send_email(sender_info).deliver
			flash[:notice] = "Message Delivered"
		else
			flash[:notice] = "Hmmm... something went wrong."
		end
		render :json => flash[:notice]
	end

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController

	def index

	end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
	
	def index 
	end

	def show
	end

end

app/controllers/snakes_controller.rb
class SnakesController < ApplicationController

	def show
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asteroids_helper.rb
module AsteroidsHelper
end

app/views/asteroids/index.html.erb
<head><title>Asteroids</title>

</head>
<body style="background-color:black;">
  <script src="../assets"></script>
   <div style="position: absolute; z-index: -2; height: 601px; width:801px;">
  <!-- image from: http://www.connectpositronic.com/blog/wp-content/uploads/2013/06/space.jpg--> 
    <img src="../assets/space.jpg" height="600" width="800"></img>
  </div>

  <script>
  var canvas = document.createElement("canvas");
  canvas.style.border = "white 1px solid";
 // canvas.style.backgroundImage = "./background.png";
  canvas.setAttribute("width", 800);
  canvas.setAttribute("height", 600);


  var body = document.getElementsByTagName("body")[0];
  //body.setAttribute("backgroundColor: black;")
  body.appendChild(canvas);

  var ctx = canvas.getContext("2d");
  ctx.font = "20px Arial";

  var game = new AsteroidsGame.Game(ctx);
  var points = game.points;
  var lives = game.lives;
  game.start();
  
  </script>
 <h3 id="instructions" style="float: right; color: white; font-size: 18px;">
    <p> Controls: </p>
    <p> Accelerate up: "w" </p>
    <p> Slow down: "s" </p>
    <p> Rotate left: "a" </p>
    <p> Rotate right: "d" </p>
    <p> Shoot: spacebar </p>
    <br> </br>
    <p> Tips: </p>
    <p> Be patient with yourself. Like the original Asteroids game,
    <br></br> the controls
        may be somewhat counter intuitive.
    </p>
    <p> Smaller asteroids are harder to hit, but are worth more points. </p>
    <p> Additional lives are rewarded at: </p>
    <p> 1000 points </p>
    <p> 2000 points </p>
    <p> 4000 points </p>
    <p> 8000 points </p>
    <p> and so on... </p>
  </h3>



</body>

<!-- TODO: Create leader board --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Homeapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Homeapp" %>">
    <%= stylesheet_link_tag "application"%>
    <%= javascript_include_tag "application"%>

    <%= csrf_meta_tags %>
  </head>
  <body>
       <%= yield %>
  </body>
</html>

app/views/resume/index.html.erb
<body id="resume">
<div id="resume-wrap">
	<div id="resume-container">
				<dl>

		<h2>Thomas Nast | tommyn@isomedia.com | (206) 947-6904</h2>

			<dt id="projects"> Projects </dt>		
			<dd>		
				
					<h4> Trello Clone </h4>
					<a href="http://www.aheadplan.com">www.aheadplan.com</a>
					<p>Full-stack development of a clone of www.trello.com. Designed to be RESTful and includes user authentication and high scalability. Ruby on Rails, JavaScript and BackBone.js and uses a postgres database. 
					</p>
				

				<h4> Asteroids </h4>
					<p>
				 	Created a modified version of the classic Asteroids video game					to be playable online. Features a continually increasing level of					difficulty. Written in JavaScript. Playable at: tdnast.me/asteroids
				 	</p> 
				

				<h4> Alfalfa  </h4>
					<p>	A ruby gem that allows for alphabetization of gemfiles in the ruby command line.  Ruby. 
					</p>
				
		 		
		 			<h4> Others </h4> 
		 			<a href="https://github.com/TND23">github.com/TND23</a>
		 			<p> Feel free to check out some of the other stuff I'm working on
		 				here at github </p>
		 		
			</dd>
			<dd class="clear"></dd>

		<dt>Education</dt>			
	
			<dd>			
				<p>B.S. Mathematics – Linfield College, 2013</p>
				<p>Associates Degree Mathematics – Shoreline Community College, 2011<p>
			</dd>

			<dd class="clear"></dd>

		<dt> Work-Study </dt>	
		<dd>		
			<p>Mathematics Homework grader for Professor Jeff Wright – Spring 2012</p>
			<p>Tutor in Calculus, Fall Semester 2012 – Spring Semester 2013</p>
		</dd>

		<dd class="clear"></dd>
		<dt id="activities"> Activities </dt> 
		<dd>			
			<p>2012 Kryptos Challenge</p>
			<p>2012 USACO Challenge</p>
			<p>2013 PRCCP Challenge </p>
			<p>2013 Kryptos Challenge</p>					
			<p>Sept.-Dec. 2013 APP Academy, San Francisco 
			<a href="http://www.appacademy.io/#p-curriculum">www.appacademy.io/#p-curriculum</a>
		</dd>


		<dd class="clear"></dd>
		<dt id="software-skills">Software / Skills</dt>
		<dd>	
			<p> Software </p>
			<p>Eclipse, Aptana, Microsoft Visual 2010, MatLab, LaTex, Sublime, Textmate. </p>

			<p> Skills </p> 
			<p> 	Ruby, Ruby on Rails, JavaScript, jQuery, Backbone.js, Java, Git, C++, SQL, HTML, CSS, Graph Theory, sense of humor </p>
		</dd>
	</div>
</div>
</body>

app/views/root/_email.html.erb
<h1>Shoot me a message!</h1>
<div id="hidden-mail">
<%= form_tag send_email_url, method: :post do %>
  <%= label_tag "sender_info[name]", "Name" %><br/>
  <%= text_field_tag "sender_info[name]" %><br />
  <%= label_tag "sender_info[email]", "Email" %><br/>
  <%= text_field_tag "sender_info[email]" %><br />
  <%= label_tag "sender_info[message]", "Message" %><br/>
  <%= text_area_tag "sender_info[message]", "", size: "60x10" %><br/>
  <%= submit_tag "Submit" %>
<% end %>
</div>

app/views/root/_slideshow.html.erb
<div id="slideshow-wrap">
    <input type="radio" id="button-1" name="controls" checked="checked"/>
    <input type="radio" id="button-2" name="controls"/>
    <input type="radio" id="button-3" name="controls"/>
    <input type="radio" id="button-4" name="controls"/>
    <input type="radio" id="button-5" name="controls"/>
    <label for="button-1" class="arrows" id="arrow-1">></label>
    <label for="button-2" class="arrows" id="arrow-2">></label>
    <label for="button-3" class="arrows" id="arrow-3">></label>
    <label for="button-4" class="arrows" id="arrow-4">></label>
    <label for="button-5" class="arrows" id="arrow-5">></label>
    <div id="slideshow-inner">
        <ul>
            <li id="slide1">
                <%= image_tag "trolle.bmp", :id => 'profile-pic' %>
                <div class="description"> 
                    <input type="checkbox" id="show-description-2"/>
                    <label for="show-description-2" class="show-description-label">I</label>
                    <div class="description-text">
                        <h2><a href="http://www.aheadplan.com">Trolle</a></h2>
                        <p>A clone of Trello and my first major creation. This is a full stack implementation of the Trello website. It was developed with rails, javascript and backbone all sitting over a postgres database.</p>
                    </div>
                </div>

            </li>
            <li id="slide2">              
              <%= image_tag "asteroids.bmp", :id => 'asteroids' %>
                <div class="description">
                    <input type="checkbox" id="show-description-1"/>
                    <label for="show-description-1" class="show-description-label">I</label>
                    <div class="description-text">
                        <h2><a href="./asteroids/index.html">Asteroids</a></h2>
                        <p> An attempt at replicating the famous "Asteroids" arcade game. So smooth so sleek. I'm considering adding sound effects and some other tidbits when I get the time. Give it a try and message me with ideas!</p>
                    </div>
                </div>
            </li>

            <li id="slide3">
                <%= image_tag "snake.bmp", :id => 'snake' %>
                    <div class="description">
                    <input type="checkbox" id="show-description-3"/>
                    <label for="show-description-3" class="show-description-label">I</label>
                    <div class="description-text">
                        <h2><a href="./snakes/index.html">Snake</a></h2>
                        <p>Snake, the game. I'll probably also get around to improving this at some point. Have fun!</p>
                    </div>
                </div>
            </li>
            <li id="slide4">
                <%= image_tag "gem.bmp", :id => 'gem' %>
                <div class="description">
                    <input type="checkbox" id="show-description-4"/>
                    <label for="show-description-4" class="show-description-label">I</label>
                    <div class="description-text">
                        <h2><a href="https://github.com/tnd23/alfalfa">Alfalfa</a></h2>
                        <p>My first gem! It's a silly little thing that allows you to run Alfalfa.sort_gemfile to
                            alphabetize your gemfiles. </p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

app/views/root/index.html.erb
<html>
    <head>
        <title>Thomas' Webpage</title>
    </head>
    <body style="background-color: rgb(56, 63, 116)">
        <div class="navbar navbar-inverse" role="navigation" style="width:100%">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand">Thomas Nast</a>
                </div>

            </div>
        </div>
        <div class="logo" style="height: 100%;">
             
            <div style="height:100%; width:100%;">

                <div id="about-me" class="push-center" style="width: 100%; background-color: rgba(146, 118, 168, .5); z-index: 1; position: absolute;  display: none; margin-top: 0px;">
                    <p style="margin-top: 100px; color: #FFFFFF; margin-left: 10px; font-family: Segoe UI; font-size: 1.5em;"> 
                        Hi! I'm Tommy. Or Thomas. Whichever you prefer. I'm a web-developer who is migrating between San Fransisco and Seattle looking for opportunities.  For information about my resume, click the 'resume' button. To check out a small list of my personal and group projects, scroll down or click on the projects button. More of my projects are listed under my github account, which can also be found below. Now please enjoy this cheese-tastic photo of me from before I discovered what a comb was. 
                    </p>
                    <%= image_tag "web_pic1.jpg", :id => 'profile-pic' %>
                </div>
                <%= image_tag "IMG_0219.JPG", :id => 'sunset-hill' %>
            </div>                
        </div>

        <div class="navbar navbar-inverse" role="navigation" style="width:100%">
            <div class="container">
                <div class="navbar-header">
                    <ul class="nav navbar-nav" >
                        <li><a id="about-me-button" href="#about">About Me</a></li>
                        <li><a id="resume-button" href="#">Resume</a></li>
                        <li><a id="contact-me-button" href="#contact">Contact</a></li>
                        <li><p id="email-address">tommyn@isomedia.com</p></li> 
                    </ul>
                </div>
            </div>
        </div>

        <h2 id="projects-header" style="color: white;">Projects</h2>

        <%= render 'slideshow' %>
<!--         <%= render 'email' %>
 -->        <footer>
        <legend style="border-bottom: 2px solid #e5e5e5"> </legend>

        <p style="line-height: 6;"> 
            <div id="footer-left-column">
                    <a href="https://github.com/TND23/">
                        <i class="fa fa-github col-md-3 col-sm-1" style="text-shadow: 1px 1px 1px #ccc; font-size: 8em; color: rgb(59, 100, 171); margin-left: 70px; margin-top: 10px;"> 
                        </i>
                    </a> 
            </div>
            <div id="footer-right-column">
                    <a href="http://linkedin.com/pub/thomas-nast/6a/747/349/">
                        <i class="fa fa-linkedin col-md-3 col-sm-1" style="text-shadow: 1px 1px 1px #000; font-size: 8em; color: rgb(255, 255, 255); margin-left: 70px; margin-top: 10px;">
                        </i>
                    </a>
                </div>
        </p>
        </footer>       



    </body>
    <script>
        $("#about-me-button").click(function(){
            var about_me = $("#about-me");
            var default_pic = $("#default-pic");
            about_me.toggle("visible");
        });

        $('#resume-button').click(function(){
            var r=confirm("View my resume online?");
            if (r==true){
                $('#resume-button').attr({target: '_blank', href: './resume'});
            }       
        });

        $('#contact-me-button').click(function(){
            var my_email = $("#email-address");
            my_email.toggle("visible");
        });
    </script>
</html>

app/views/snakes/show.html.erb
<html>
	<body>

		<button type="button" style="margin-top: 0px;" onclick="board.setMode('rainbow');">Rainbow mode!</button>
		<button type="button" onclick="board.setMode('normal'); ">Normal mode!</button>
		<button type="button" onclick="board.setMode('obn'); ">Obnoxious mode!</button>
		<button type="button" onclick="board.setMode('obn2'); ">Obnoxious mode 2!</button>

		<script>
			var board = new Board.GameBoard();
			var game = new SnakeGame.Game();
			var body = document.getElementsByTagName("body")[0];
			board.create(body);
			game.start();
		</script>
	</body>

	<p> Left: a or left on arrow pad </p>
	<p> Up: w or up on arrow pad </p>
	<p style="margin-left: 440px; "> Down: s or down on arrow pad </p>
	<p style="margin-left: 440px; "> Right: d or right on arrow pad </p>
	<p style="margin-left: 440px; margin-bottom: 0px;"> Pause: space bar </p>
</html>